### ISSUE TITLE
Normalizing features

### ISSUE THREAD

**Issue by rahulvigneswaran** [Reza-Safdari/SimSiam#4]
Why do you normalize only the train features and not the val features?

https://github.com/Reza-Safdari/SimSiam-91.9-top1-acc-on-CIFAR10/blob/f7365684399b1e6895f81ff059eaa4e2b8c73608/simsiam/validation.py#L62

**Comment by Reza-Safdari** [comment]
It is just a mistake and I'll fix this issue asap.
